#!/usr/bin/env bash

set -e

bazel_target_files() {
	bazel cquery --enable_bzlmod --output files "$1" 2> /dev/null | xargs -l realpath
}

SCRIPT_DIRECTORY="$(dirname -- "${BASH_SOURCE[0]}")"
OLD_PWD="$PWD"

cd "$SCRIPT_DIRECTORY"

bazel build --enable_bzlmod //src/interpreter //src/standard_library

INTERPRETER_PATH="$(bazel_target_files //src/interpreter)"
STANDARD_LIBRARY_DIRECTORY="$(bazel_target_files //src/standard_library)"
STARTUP_FILE_PATH="$SCRIPT_DIRECTORY/src/startup_file.krait"

cd "$OLD_PWD"

KRAIT_PATH="$STANDARD_LIBRARY_DIRECTORY:$KRAIT_PATH" \
	KRAIT_STARTUP="$STARTUP_FILE_PATH" \
	KRAIT_STARTUP_EXCLUDE="$STANDARD_LIBRARY_DIRECTORY:$KRAIT_PATH" \
	"$INTERPRETER_PATH" \
	"$@"
